name: Component testing
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: npm run cypress-run


