name: Push CI
on: [push]
jobs:
  component testing on chrome:
    runs-on: ubuntu-20.04
    name: Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          command: cypress run --component
          record: true
  component testing on firefox:
    runs-on: ubuntu-20.04
    name: Firefox
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: firefox
          command: cypress run --component
          record: true


